theme: just-the-docs
name: Dwarf debugger
title: Dwarf
description: Full featured multi arch/os debugger built on top of PyQt5 and frida
baseurl: /DwarfWebsite

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

color_scheme: "dark"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
