gems:
  - jekyll-remote-theme

remote_theme: allejo/jekyll-docs-theme

name: Dwarf debugger

baseurl: DwarfWebsite

project:
  version: 1.0.0
  download_url: https://github.com/iGio90/Dwarf

license:
  software: GPL-3.0 License
  software_url: https://github.com/iGio90/Dwarf/blob/master/LICENSE

links:
  header:
    - title: GitHub
      url: https://github.com/iGio90/Dwarf
  footer:
    - title: GitHub
      url: https://github.com/iGio90/Dwarf
    - title: Issues
      url: https://github.com/iGio90/Dwarf/issues?state=open

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
  github:
    user: iGio90
    repo: Dwarf
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
